NumPy - Numerical Python

Advantages of Numoy Arrays:
  1. Allows several Mathematical Opperations
  2. Faster Opperations

In [1]:
import numpy as np

List vs NumMPy - Time Taken

In [2]:
from time import process_time

Time taken by a list

In [3]:
python_list = [i for i in range(10000)]

start_time = process_time()
python_list = [i + 5 for i in python_list]
end_time = process_time()
print(end_time - start_time)

0.0006637289999993357


Time taken bys using Numpy arrays

In [5]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()
np_array += 5
end_time = process_time()
print(end_time - start_time)


0.001170293999999572


Numpy Arrays

In [2]:
import numpy as np
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [3]:
#creating a 1 dim array

import numpy as np

a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [4]:
a.shape

(5,)

In [7]:
#creating a 2 dim array

b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
b.shape

(2, 4)

In [8]:
#data type array

c = np.array([1,2,3,4,5], dtype = float)
print(c)

[1. 2. 3. 4. 5.]


Initial Placeholders in numpy arrays

In [9]:
#creating a numpy array of zeros

x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
#creating a numpy array of ones
z = np.ones((3,3),dtype= int)
print(z)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [12]:
#arrays of a particular value

z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [13]:
#creating an idientity matrix
# 4 gives 4x4 matrix

a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
# creating a numpy array with random values

b = np.random.rand(4,3)
print(b)

[[0.76335786 0.28028551 0.35756337]
 [0.67838435 0.44913996 0.84760575]
 [0.3352704  0.42130027 0.33928864]
 [0.53632029 0.50487098 0.42879616]]


In [19]:
#random integer array within a specific range

c = np.random.randint(0,10,(3,5))
print(c)

[[0 2 0 4 2]
 [0 7 4 5 4]
 [7 0 7 6 4]]


In [20]:
#array of evenly spaced values
#evenly spaced 5 values b/w 10-30

d= np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [21]:
#array of evenly spaced values --> specifying the step(5)

e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [22]:
#converting a list to numpy arrauy

list2 =[1,2,3,4,5,6]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[1 2 3 4 5 6]


numpy.ndarray

Analysing a numpy array

In [23]:
c = np.random.randint(10,100,(5,5))
print(c)

[[12 70 33 20 35]
 [78 57 50 27 77]
 [78 93 11 57 55]
 [79 52 41 79 86]
 [19 35 79 95 18]]


In [24]:
#array shape
print(c.shape)

(5, 5)


In [25]:
#array dimension
print(c.ndim)

2


In [26]:
#array size / no. of elements
print(c.size)

25


In [27]:
#checking the data type
print(c.dtype)

int64


Mathematical opperations on a numpy array

In [28]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) # concatinates 2 lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [29]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[5 4 5]
 [4 4 5]
 [1 1 8]]
[[13 18 17]
 [13 17 10]
 [17 13 13]]


In [30]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[18 22 22]
 [17 21 15]
 [18 14 21]]
[[ -8 -14 -12]
 [ -9 -13  -5]
 [-16 -12  -5]]
[[ 65  72  85]
 [ 52  68  50]
 [ 17  13 104]]
[[0.38461538 0.22222222 0.29411765]
 [0.30769231 0.23529412 0.5       ]
 [0.05882353 0.07692308 0.61538462]]


In [31]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[18 22 22]
 [17 21 15]
 [18 14 21]]
[[ -8 -14 -12]
 [ -9 -13  -5]
 [-16 -12  -5]]
[[ 65  72  85]
 [ 52  68  50]
 [ 17  13 104]]
[[0.38461538 0.22222222 0.29411765]
 [0.30769231 0.23529412 0.5       ]
 [0.05882353 0.07692308 0.61538462]]


Array Manipulation

In [32]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)


[[9 5 7]
 [2 9 6]]
(2, 3)


In [33]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)


[[9 2]
 [5 9]
 [7 6]]
(3, 2)


In [34]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)


[[4 8 1]
 [4 4 0]]
(2, 3)


In [35]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[4 4]
 [8 4]
 [1 0]]
(3, 2)


In [36]:

# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[6 5 7]
 [3 5 5]]
(2, 3)


In [37]:
b = a.reshape(3,2)
print(b)
print(b.shape)


[[6 5]
 [7 3]
 [5 5]]
(3, 2)
