In [1]:
import numpy as np

Matrix addition and subtraction

can be done only if the shape is same

In [3]:
A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])
sum = A + B
print(sum)

difference = A - B
print(difference)

[[ 8 10]
 [12 14]]
[[-4 -4]
 [-4 -4]]


Multiplying a matrix by a scalar



In [5]:
x = 5
y = np.random.randint(10, size=(4,4))
product = np.multiply(x,y)
print(product)

[[30 30  0 45]
 [35 25 30 10]
 [ 0 35 35 20]
 [15 30 20 30]]


Element wise matrix multiplication

In [6]:
matrix_3 = np.random.randint(10, size=(3,3))
matrix_4 = np.random.randint(10, size=(3,3))
product = np.multiply(matrix_3, matrix_4)
print(product)


[[18 16 15]
 [40 63 10]
 [ 0  0  3]]
