In [2]:
import numpy as np

creating a matrix using numpy

In [3]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [4]:
matrix_2 = np.array([[10,35,45],[50,64,80],[20,15,90]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


creating matrices with random values





In [5]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.40242692 0.96574788 0.05718219]
 [0.27812335 0.68208696 0.77066467]
 [0.83086235 0.73634957 0.54120523]]


creating matrices with random int values


In [6]:
random_integer_matrix = np.random.randint(100, size=(4,5))
print(random_integer_matrix)

[[84 65  5 27 14]
 [88 42  4 39 42]
 [30 89 84 50  8]
 [43 68 75  3 41]]


Matrix with all the values as 1

In [7]:


matrix_3 = np.ones((2,3), dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


Null matrix

In [8]:
null_matrix = np.zeros((7,7))
print(null_matrix)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


Identity matrix

In [9]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
identity_matrix = np.eye(5,5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Transpose of a matrix

In [11]:
a = np.random.randint(100, size=(4,5))
print(a)

[[ 1 40 92 41 19]
 [69 28 14 22 10]
 [52 65 28 11 28]
 [82 71 88 27  1]]


In [12]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[ 1 69 52 82]
 [40 28 65 71]
 [92 14 28 88]
 [41 22 11 27]
 [19 10 28  1]]
